### PR TITLE
feat: AWS IAM naming convention for ARN paths

### PR DESCRIPTION
**Pull request by bilbercode**

### CODE REVIEW

**Comment by hectorhuertas** [comment]
User needs to have your team's permission boundary, like https://github.com/utilitywarehouse/terraform/blob/flexible-boundaries/aws/dev/sys-log/mongo-backup.tf#L1-L4

I think the path prefix is not going to work. To avoid colliding teams and prefixes, the prefix on the resource name should be `telecom-` or `telco-`. A user "born" in `/telecom/myname` won't be valid. Our intended use case was the team name/prefix to be used in the name and live in the root path. The reason being that user and role names need to be unique, and the path is not counted towards this uniqueness.

Would it be possible to use your team in the user name instead of the path?

**Comment by bilbercode** [comment]
Sure

**Comment by hectorhuertas** [comment]
Thanks

**Comment by hectorhuertas** [comment]
Still needs `permissions_boundary = "arn:aws:iam::${var.account_id}:policy/sys-telecom-boundary"`

**Comment by bilbercode** [comment]
how about 
```
resource "aws_iam_user" "user" {
  name = "${format("/%s/", replace(var.team, "/^uw-/", ""))}-${var.name}"
  permissions_boundary = "arn:aws:iam::${var.account_id}:policy/sys-${format("/%s/", replace(var.team, "/^uw-/", ""))}-boundary"
  tags {
    terraform = "Managed by terraform"
    team = "${format("/%s/", replace(var.team, "/^uw-/", ""))}"
  }
}
```
?

**Comment by bilbercode** [comment]
although the account_id part would be new, however it would be more inline with the GCP module

**Review by hectorhuertas — APPROVED** [review]

**Comment by bilbercode** [comment]
cheers dude

**Comment by hectorhuertas** [comment]
thanks to you!

**Review by jakekeeys — APPROVED** [review]

**Pull request merged**
